export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const ADD_USER_DATA = 'ADD_USER_DATA';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const RECEIVED_USER_DATA = 'RECEIVED_USER_DATA';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

